config/routes.rb
Technet::Application.routes.draw do
  resources :models

  resources :tickets

  resources :copiers

  devise_for :users

end

app/models/copier.rb
class Copier < ActiveRecord::Base
  attr_accessible :location, :serial, :model_id
  has_many :tickets, :dependent => :destroy
  belongs_to :user
  belongs_to :model
  validates :user_id, presence: true
end

app/models/model.rb
class Model < ActiveRecord::Base
  attr_accessible :brand, :name
  has_many :copiers
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :counter, :issue, :copier_id, :status
  belongs_to :copier
#  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :copiers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/copiers_controller.rb
class CopiersController < ApplicationController
  before_filter :authenticate_user!
  # GET /copiers
  # GET /copiers.json
  def index
    @copiers = Copier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @copiers }
    end
  end

  # GET /copiers/1
  # GET /copiers/1.json
  def show
    @copier = Copier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @copier }
    end
  end

  # GET /copiers/new
  # GET /copiers/new.json
  def new
  #  @copier = Copier.new
     @copier = current_user.copiers.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @copier }
    end
  end

  # GET /copiers/1/edit
  def edit
    #@copier = Copier.find(params[:id])
    @copier = current_user.copiers.find(params[:id])

  end

  # POST /copiers
  # POST /copiers.json
  def create
    #@copier = Copier.new(params[:copier])
    @copier = current_user.copiers.new(params[:copier])

    respond_to do |format|
      if @copier.save
        format.html { redirect_to @copier, notice: 'Copier was successfully created.' }
        format.json { render json: @copier, status: :created, location: @copier }
      else
        format.html { render action: "new" }
        format.json { render json: @copier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /copiers/1
  # PUT /copiers/1.json
  def update
    #@copier = Copier.find(params[:id])
    @copier = current_user.copiers.find(params[:id])

    respond_to do |format|
      if @copier.update_attributes(params[:copier])
        format.html { redirect_to @copier, notice: 'Copier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @copier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copiers/1
  # DELETE /copiers/1.json
  def destroy
    #@copier = Copier.find(params[:id])
    @copier = current_user.copiers.find(params[:id])
    @copier.destroy

    respond_to do |format|
      format.html { redirect_to copiers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  # GET /models
  # GET /models.json
  def index
    @models = Model.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/new
  # GET /models/new.json
  def new
    @model = Model.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @model }
    end
  end

  # GET /models/1/edit
  def edit
    @model = Model.find(params[:id])
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(params[:model])

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render json: @model, status: :created, location: @model }
      else
        format.html { render action: "new" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /models/1
  # PUT /models/1.json
  def update
    @model = Model.find(params[:id])

    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    #@ticket = Ticket.new(params[:ticket])
    #@ticket = Ticket.new(params[:ticket,:copier_id => params[:copierid]])
    @ticket = Ticket.new(params[:ticket])
    @ticket.copier_id = params[:ticket][:copier_id]
    #@ticket.issue = 

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/copiers_helper.rb
module CopiersHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/copiers/_form.html.erb
<%= simple_form_for(@copier) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :serial %>
    <%= f.input :location %>
	<%= f.collection_select(:model_id, Model.all, :id, :name, :prompt => "Select a prospect") %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/copiers/edit.html.erb
<h1>Editing copier</h1>

<%= render 'form' %>

<%= link_to 'Show', @copier %> |
<%= link_to 'Back', copiers_path %>

app/views/copiers/index.html.erb
<h1>Listing copiers</h1>

<table>
  <tr>
    <th>Serial</th>
    <th>Location</th>
    <th>Model Id</th>
    <th></th>
    <th></th>
  </tr>

<% @copiers.each do |copier| %>
  <% if current_user == copier.user %>
  <tr>
    <td><%= copier.serial %></td>
    <td><%= copier.location %></td>
    <td><%= Model.find(copier.model_id.to_i).name %></td>
    
    <td><%= link_to 'Show', copier %></td>
    <td><%= link_to 'Edit', edit_copier_path(copier) %></td>
    <td><%= link_to 'Destroy', copier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <!--<td><%= hidden_field :copier_id, :value => copier.id %> </td>> !-->

    <td><%= link_to 'Zamow Toner', new_ticket_path(:copier_id => copier, :type => "toner") %> </td>
    <td><%= link_to 'Zamow Serwis', new_ticket_path(:copier_id => copier) %> </td>
  </tr>
<% end %>

<% end %>
</table>

<br />

<%= link_to 'New Copier', new_copier_path %>

app/views/copiers/new.html.erb
<h1>New copier</h1>

<%= render 'form' %>

<%= link_to 'Back', copiers_path %>

app/views/copiers/show.html.erb
MOVE THIS FILE TO TICKETS
<h1>Listing tickets</h1>

<p>
  <b>Serial:</b>
  <%= @copier.serial %>
</p>

<p>
  <b>Location:</b>
  <%= @copier.location %>
</p>

<%= Model.find(@copier.model_id.to_i).name %>

<table>
  <tr>
    <th>Issue</th>
    <th>Counter</th>
    <th>Copier id</th>
    <th>Status</th>
    <th></th>
  </tr>

<% @tickets = Ticket.all %>
<% @tickets.each do |ticket| %>
<% if ticket.copier_id.to_i == params[:id].to_i %> 
  <tr>
    <td><%= ticket.issue %></td>
    <td><%= ticket.counter %></td>
    <td><%= ticket.copier_id %></td>
    <td><%= ticket.status %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/copiers/show1.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Serial:</b>
  <%= @copier.serial %>
</p>

<p>
  <b>Location:</b>
  <%= @copier.location %>
</p>


<%= link_to 'Edit', edit_copier_path(@copier) %> |
<%= link_to 'Back', copiers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
            <% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>

<%= yield %>

</body>
</html>

app/views/models/_form.html.erb
<%= simple_form_for(@model) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :brand %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', @model %> |
<%= link_to 'Back', models_path %>

app/views/models/index.html.erb
<h1>Listing models</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Brand</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @models.each do |model| %>
  <tr>
    <td><%= model.name %></td>
    <td><%= model.brand %></td>
    <td><%= link_to 'Show', model %></td>
    <td><%= link_to 'Edit', edit_model_path(model) %></td>
    <td><%= link_to 'Destroy', model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Model', new_model_path %>

app/views/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @model.name %>
</p>

<p>
  <b>Brand:</b>
  <%= @model.brand %>
</p>


<%= link_to 'Edit', edit_model_path(@model) %> |
<%= link_to 'Back', models_path %>

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :issue %>
    <%= f.input :counter %>
  	<%= f.hidden_field :copier_id, :value => params[:copier_id] %>
  	<%= f.hidden_field :status, :value => "open" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Issue</th>
    <th>Counter</th>
    <th>Copier id</th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.issue %></td>
    <td><%= ticket.counter %></td>
    <td><%= ticket.copier_id %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<% if params[:type] != NIL %>
<% if params[:type] == "toner"%>
<h1>Zamów Toner</h1>
<%= render 'form' %>
<% else %>
<h1>Zamów Serwis</h1>
<%= render 'form' %>
<%end%>
<%else%>
brak wskaznika
<%end%>
<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue:</b>
  <%= @ticket.issue %>
</p>

<p>
  <b>Counter:</b>
  <%= @ticket.counter %>
</p>

<p>
  <b>Status:</b>
  <%= @ticket.status %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>